version: '3'
services:
  myapp-main:
    image: keyin/atlassearch
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:postgresql://locations.cotu0q1tlpsq.us-east-1.rds.amazonaws.com/Locations
      - spring.secondDatasource.url=locations-mysql.cotu0q1tlpsq.us-east-1.rds.amazonaws.com/locationsMysql